name: CI PRUEBAS automatizadas (develop)p1

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:

jobs:
  test_application:
    name: "Ejecutar pruebas automatizadas"
    runs-on: ubuntu-latest
    env:
      SUPA_BASE_URL: ${{ secrets.SUPA_BASE_URL }}
      SUPA_ANON_KEY: ${{ secrets.SUPA_ANON_KEY }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ["20.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check environment variables
        run: |
          echo "SUPA_BASE_URL: $SUPA_BASE_URL"
          echo "SUPA_ANON_KEY: ${SUPA_ANON_KEY:0:5}..."  # Muestra solo los primeros 5 caracteres por seguridad

      - name: Run tests with Vitest
        run: |
          echo "Iniciando pruebas automatizadas con Vitest..."
          npx vitest run --reporter=dot
        continue-on-error: false

      - name: Resultado final
        if: always()
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "❌ Pruebas automatizadas fallidas"
            exit 1
          else
            echo "✅ Pruebas automatizadas exitosas"
          fi
